export const tableData = [{
    snum: 1,
    name: "Urvashi",
    email: "urvashi@gmail.com",
    experience: 2,
    status: "Selected",
    department: "Node",
},
{
    snum:2,
    name: "Rinkal",
    email: "rinkal@gmail.com",
    experience: 1,
    status: "Selected",
    department: "Node",
},
{
    snum:3,
    name: "Nikhil",
    email: "nik@gmail.com",
    experience: 5,
    status: "Aligned",
    department: "Marketcube",
},
{
    snum:4,
    name: "Srishti",
    email: "srishti@gmail.com",
    experience: 2,
    status: "Aligned",
    department: "Frontend",
},
{
    snum:5,
    name: "Akash",
    email: "akash@gmail.com",
    experience: 2,
    status: "Aligned",
    department: "PHP JS",
},{
    snum:6,
    name: "Ajay",
    email: "ajcool@gmail.com",
    experience: 4,
    status: "Selected",
    department: "Node",
}
]